originalImage = imread('C:\Users\Venka\OneDrive\Pictures\wallpaperflare.com_wallpaper (3).jpg');
figure;
imshow(originalImage);
title("Original Image");
PSF = fspecial("gaussian",5,40);
BlurredImage = imfilter(originalImage,PSF,"symmetric","conv");
figure;
imshow(BlurredImage);
title("Blurred");
V = .002;
BlurredNoisyImage = imnoise(BlurredImage,"gaussian",0,V);
figure;
imshow(BlurredNoisyImage);
title("Blurred & Noisy");
luc1 = deconvlucy(BlurredNoisyImage,PSF,5);
figure;
imshow(luc1);
title("Restored Image, NUMIT = 5");
luc1_cell = deconvlucy({BlurredNoisyImage},PSF,5);
luc2_cell = deconvlucy(luc1_cell,PSF);
luc2 = im2uint8(luc2_cell{2});
figure;
imshow(luc2);
title("Restored Image, NUMIT = 15");
DAMPAR = im2uint8(3*sqrt(V));
luc3 = deconvlucy(BlurredNoisyImage,PSF,15,DAMPAR);
figure;
imshow(luc3);
title("Restored Image with Damping, NUMIT = 15");